import palette from './palette.js';

export default {
    content: [],
    target: '> 0.5%, last 2 major versions, Firefox ESR, not dead',
    ignore: [],
    visitors: {
        concatenateNestedClasses: true,
        emMediaQueries: true,
        fontPxToRem: true,
        generateCustomProperties: true,
    },
    uno: {
        rules: [],
        variants: [],
    },
    tokens: {
        breakpoints: {
            'xs': 480,
            'sm': 640,
            'md': 800,
            'lg': 1024,
            'xl': 1280,
            '2xl': 1600,
        },
        colors: {
            'primary': '#502a7a',
            'white': '#fff',
            'black': '#000',
            'gray': palette.gray,
            'red': palette.red,
            'orange': palette.orange,
            'yellow': palette.yellow,
            'green': palette.green,
            'teal': palette.teal,
            'blue': palette.blue,
            'purple': palette.purple,
            'magenta': palette.magenta,
            'pink': palette.pink,
            'text': `var(--color-gray-80, ${palette.gray[80]})`,
            'link': `var(--color-blue-55, ${palette.blue[55]})`,
            'link-hover': `var(--color-blue-65, ${palette.blue[65]})`,
            'border': `var(--color-gray-30, ${palette.gray[30]})`,
            'ring': palette.blue[55] + 'dd',
        },
        containerWidth: '80rem', // 1280px
        containerPadding: 'max(1rem, min(5vw, 2rem))',
        ring: '0 0 0 2px var(--color-ring)',
        offsetRing: '0 0 0 1px #fff, 0 0 0 3px var(--color-ring)',
        fontFamily: {
            'sans': 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
            'serif': 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
            'monospace': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
            'base': ({ fontFamily }) => fontFamily.sans,
            'headings': ({ fontFamily }) => fontFamily.sans,
        },
        fontSize: {
            'xs': '0.65rem',
            'sm': '0.8rem',
            'caption': '0.9rem',
            'base': '1rem',
            'lg': '1.12rem',
            'xl': '1.25rem',
            'h1': '2.44rem',
            'h2': '1.95rem',
            'h3': '1.56rem',
            'h4': '1.25rem',
        },
        fontWeight: {
            'thin': 100,
            'extralight': 200,
            'light': 300,
            'normal': 400,
            'medium': 500,
            'semibold': 600,
            'bold': 700,
            'extrabold': 800,
            'black': 900,
        },
        gutter: '2rem',
        letterSpacing: {
            0: '0',
            1: '0.025em',
            2: '0.05em',
            3: '0.075em',
            4: '0.1em',
        },
        lineHeight: {
            'base': 1.6,
        },
        radius: {
            'sm': '0.25rem',
            'md': '0.5rem',
            'lg': '1rem',
            'DEFAULT': ({ radius }) => radius.md,
        },
        boxShadow: {
            '2xs': '0 1px rgb(0 0 0 / 0.05)',
            'xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
            'sm': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
            'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
            'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
            'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
            '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        },
        insetBoxShadow: {
            '2xs': 'inset 0 1px rgb(0 0 0 / 0.05)',
            'xs': 'inset 0 1px 1px rgb(0 0 0 / 0.05)',
            'sm': 'inset 0 2px 4px rgb(0 0 0 / 0.05)',
        },
    }
};
